import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { NextAuthProvider } from "./providers";
import { CookiesProvider } from "next-client-cookies/server";
import { options } from "./api/auth/[...nextauth]/options";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  console.log("layout.tsx: ", session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <NextAuthProvider>
            <ToastContainer />
            {!!session && <Navbar />}
            {!session && <Navbar />}

            <div className="container h-full pt-12">{children}</div>
          </NextAuthProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
