name: SE356 Frontend CI/CD Pipeline

env:
  ENV_FILE_PATH: /root/se356/frontend/env_file/.env

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./*"
          target: "/root/se356/frontend/source"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cp ${{ env.ENV_FILE_PATH }} /root/se356/frontend/source/
            cd /root/se356/frontend/source/  
            sudo docker compose down       
            docker compose up --build -d
